use_frameworks!

platform :ios, '9.0'

target 'CategoryRelyon_Example' do
  pod 'CategoryRelyon', :path => '../',:subspecs => ['LoadCategory']

  target 'CategoryRelyon_Tests' do
    inherit! :search_paths

    
  end
end
